import type { Metadata } from 'next'
import { Poppins, Roboto } from 'next/font/google'
import './globals.css'
import { Header } from '../components/Header'
import { Sidebar } from '../components/Sidebar'
import { ThemeProvider } from '../providers/theme-provider'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export const roboto_init = Roboto({
	subsets: ['latin'],
	weight: ['400', '500', '700'],
	variable: '--font-primary',
})

export const poppins_init = Poppins({
	subsets: ['latin'],
	weight: ['400', '500', '700'],
	variable: '--font-secondary',
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="pt-BR" suppressHydrationWarning>
			<head>
				<link
					rel="stylesheet"
					type="text/css"
					href="https://cdn3.devexpress.com/jslib/24.1.3/css/dx.material.blue.light.css"
				/>
			</head>
			<body className={`${roboto_init.variable} ${poppins_init.variable}`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange
				>
					<main className="w-screen h-screen font-primary bg-background-light dark:bg-background-dark text-black dark:text-white relative pl-[65px]">
						<Sidebar />
						<Header />
						{children}
					</main>
				</ThemeProvider>
			</body>
		</html>
	)
}
