import type { Metadata } from 'next'
import { Poppins, Roboto } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export const roboto_init = Roboto({
	subsets: ['latin'],
	weight: ['400', '500', '700'],
	variable: '--font-primary',
})

export const poppins_init = Poppins({
	subsets: ['latin'],
	weight: ['400', '500', '700'],
	variable: '--font-secondary',
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html className="dark" lang="pt-BR">
			<body className={`${roboto_init.variable} ${poppins_init.variable}`}>
				{children}
			</body>
		</html>
	)
}
