@base_url=http://localhost:3333

GET {{base_url}}

###
POST {{base_url}}
Content-Type: multipart/form-data

{
  "name": "Product",
  "description": "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
  "value": 15,
  "quantity": 5,
  "file": "TYPE FILE"
}

###
DELETE {{base_url}}
Content-Type: application/json

{
  "productsId": ["clxpfhbkq0000dpy8gmt3dc26", "clxpfetzp00001umtf989aojs"]
}
